Sync up with latest AOSP changes
sm7325: techpack: msm: samsung: reset finger mask state on screen off
Change-Id: I70aade584e97b8031434eceb73c8e90770b1e7f5
Signed-off-by: Ruchit <risenid@duck.com>

sm7325: dts: get rid of in-kernel vendor mounting

ERROR: recovery: [libfs_mgr] Error updating for slotselect

Change-Id: I03ceac62b333f6440dc4b7653b1633e9add27fd4
Signed-off-by: Ruchit <risenid@duck.com>

sm7325: input: sec_input: synaptics: Add sysfs to track FOD pressed state

/sys/class/sec/tsp/input/fod_pressed
0 -> not pressed
1 -> pressed

Change-Id: Ifb2f432b1286bfc2a76a7c462326562569942ae5
Signed-off-by: Ruchit <risenid@duck.com>

techpack: audio: tfa98xx: add error translation routine

Change-Id: I4d1d428f0306bbe6bb25d8beab8a74307aaeadf7
Signed-off-by: Ruchit <risenid@duck.com>

qcacmn: Dynamically allocate memory for ipa_wdi_conn_in_params

Currently struct ipa_wdi_conn_in_params occupies 1588 bytes and putting
it on the stack is rather expensive, which could potentially lead to
stack corruption.

Fix is to reduce stack usage in dp_ipa_setup by dynamically allocating
struct ipa_wdi_conn_in_params on the heap.

Change-Id: I8f71f44906a5c95f37627f7573b57b7825daaa7e
CRs-Fixed: 2852027
Signed-off-by: Ruchit <risenid@duck.com>

sm7325: input: sec_input: stm: force enable hover proximity sensor

The sensors HAL passes "1" to /sys/class/sec/tsp/ear_detect_enable, which leads to the proximity sensor being enabled.

So far it seems like 1 enables touch proximity, whereas 3 enables both hover proximity and touch proximity. It is yet to figure out if and what 2 does, but for now force enable the hover feature by altering the value passed by the HAL to 3.

Only enable hovering when the screen is not in LPM because turning on the hover feature breaks proximity when in LPM. While in LPM touch proximity will be used, otherwise touch proximity will be disabled.

Additionally we need to reset fod_pressed to 0 once we're entering LPM because enabling hovering sometimes prevents the driver from running into FTS_SPONGE_EVENT_GESTURE_ID_FOD_RELEASE, leaving fod_pressed sysfs at 1.

Change-Id: I7d77a79772d4661c5d1dc7dc64e144299c8f26d5
Signed-off-by: Simon1511 <me@simon1511.de>

techpack: msm: sde: Fallback to PCC for color invert

* After the conversion from PCC to CSC for color trasformation,
   all filters work correctly and are converted properly to CSC,
   except for the color invert filter
 * This filter is the only one using the `c` constant coefficient
   in PCC, and it's almost impossible to conver to CSC, because
   the PCC reported values are far off from the regular scale of
   values that is being used, which makes converting the filter
   to CSC extra complex
 * To work around this, force PCC for all color filters when color
   invert is enabled, which has the downside of not behaving as well
   as CSC when using FOD, but still works just as good for all
   other contexts
 * We can use the `c` coefficient to understand if color invert is
   enabled, since this is the only color filter that sets the value
   to anything other than 0 (`32640`).

Simon1511: check for blob being NULL

Change-Id: I097413be9c519c22ee71483bdc084512f05e0465
Signed-off-by: Ruchit <risenid@duck.com>

input: Sync switch event codes with upstream linux

* They are checked as of https://android.googlesource.com/platform/frameworks/native/+/9762ac9c1b813850379f55dfc2bd6698b8c96c64,
  values > upstream linux SW_MAX will now cause a system_server crash

Change-Id: Ib26f230bfa663f78ec17fc91890679210558ad60
Signed-off-by: Ruchit <risenid@duck.com>